<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Music Publishing Administration Agreement</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111827;
            font-size: 13px;
            line-height: 1.7;
        }

        .page {
            padding: 30px;
        }

        .title {
            text-align: center;
            font-size: 22px;
            font-weight: bold;
            margin-bottom: 25px;
        }

        .section {
            margin-bottom: 18px;
        }

        .label {
            font-weight: bold;
        }

        .signature-box {
            margin-top: 50px;
            border-top: 1px solid #111827;
            width: 280px;
            padding-top: 8px;
        }

        .footer {
            margin-top: 60px;
            font-size: 11px;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="page">
    <div class="title">Music Publishing Administration Agreement</div>

    <div class="section">
        This Music Publishing Administration Agreement is entered into by and between
        the platform administrator and the registered user named below.
    </div>

    <div class="section">
        <span class="label">Registered User Name:</span> {{ $user->name }}
    </div>

    <div class="section">
        <span class="label">Email:</span> {{ $user->email }}
    </div>

    <div class="section">
        <span class="label">Agreement Date:</span> {{ $signedDate }}
    </div>

    <div class="section">
        By registering and verifying this account, the user agrees to allow the platform
        to administer music publishing information, album records, song registration data,
        payout information, and related administration processes.
    </div>

    <div class="section">
        The user understands that album and song records may be reviewed, approved,
        completed, updated, or managed by the administrator according to the platform
        operation policy.
    </div>

    <div class="section">
        This document is system-generated and digitally signed using the registered
        account information provided by the user.
    </div>

    <div class="signature-box">
        <div><strong>Signed Name:</strong> {{ $user->name }}</div>
        <div><strong>Date:</strong> {{ $signedDate }}</div>
    </div>

    <div class="footer">
        Generated by Music Publishing Administration System
    </div>
</div>
</body>
</html>