<x-app-layout>
    <x-slot name="header"><h2 class="text-2xl font-black">Revenue Splits</h2></x-slot>
    <div class="px-6 py-8"><div class="mx-auto max-w-7xl space-y-8">
        @if(session('success'))<div class="border-2 border-black bg-emerald-300 p-4 font-bold">{{ session('success') }}</div>@endif
        <section><h3 class="mb-4 text-xl font-black">Pending Change Requests</h3><div class="space-y-4">
            @forelse($requests as $change)<div class="border-2 border-black bg-amber-100 p-5 shadow-[4px_4px_0_#000]"><div class="font-black">{{ $change->album->title }}</div><div class="text-sm font-bold text-black/60">Requested by {{ $change->album->artist->artist_name }} · {{ $change->reason }}</div><div class="my-4 grid gap-3 md:grid-cols-2"><div class="border-2 border-black bg-white p-3"><div class="text-xs font-black uppercase text-black/50">Current</div><div class="font-bold">Primary: {{ $change->current_splits['primary_artist_percentage'] ?? 100 }}%</div>@foreach($change->current_splits['collaborators'] ?? [] as $split)<div class="text-sm font-bold">{{ $split['artist_name'] }}: {{ $split['percentage'] }}%</div>@endforeach</div><div class="border-2 border-black bg-emerald-50 p-3"><div class="text-xs font-black uppercase text-black/50">Proposed</div><div class="font-bold">Primary: {{ $change->proposed_splits['primary_artist_percentage'] ?? 100 }}%</div>@foreach($change->proposed_splits['collaborators'] ?? [] as $split)<div class="text-sm font-bold">{{ $split['artist_name'] }}: {{ $split['percentage'] }}%</div>@endforeach</div></div><div class="flex flex-wrap gap-3"><form method="POST" action="{{ route('admin.revenue-splits.approve', $change) }}" class="flex gap-2">@csrf<input type="text" name="admin_note" placeholder="Admin note" class="border-2 border-black px-3 py-2 text-sm"><button class="border-2 border-black bg-emerald-300 px-4 py-2 font-black">APPROVE</button></form><form method="POST" action="{{ route('admin.revenue-splits.reject', $change) }}" class="flex gap-2">@csrf<input type="text" name="admin_note" required placeholder="Reason required" class="border-2 border-black px-3 py-2 text-sm"><button class="border-2 border-black bg-red-200 px-4 py-2 font-black">REJECT</button></form></div></div>
            @empty<div class="border-2 border-black bg-white p-6 font-bold text-black/40">No pending change requests.</div>@endforelse
        </div></section>
        <section><h3 class="mb-4 text-xl font-black">Collaborator Splits</h3><div class="overflow-x-auto border-2 border-black bg-white"><table class="w-full text-sm"><thead><tr class="border-b-2 border-black"><th class="p-3 text-left">Release</th><th class="p-3 text-left">Master</th><th class="p-3 text-left">Primary</th><th class="p-3 text-left">Collaborators</th><th class="p-3">Status</th><th class="p-3">Versions</th></tr></thead><tbody>
            @forelse($releases as $release)<tr class="border-b border-black/10"><td class="p-3 font-black"><a class="underline" href="{{ route('admin.releases.show', $release) }}">{{ $release->title }}</a></td><td class="p-3 font-bold">{{ $release->artist->activeMasterAccount()?->name ?? 'Standalone' }}</td><td class="p-3 font-bold">{{ $release->artist->artist_name }} ({{ 100 - $release->collaboratingArtists->sum(fn($a) => $a->pivot->share_percentage) }}%)</td><td class="p-3">@foreach($release->collaboratingArtists as $artist)<div class="font-bold">{{ $artist->artist_name }} — {{ $artist->pivot->share_percentage }}%</div>@endforeach</td><td class="p-3 text-center font-black">{{ $release->splitsAreLocked() ? 'LOCKED' : 'DRAFT' }}</td><td class="p-3 text-center font-black">{{ $release->splitVersions->count() }}</td></tr>
            @empty<tr><td colspan="6" class="p-8 text-center font-bold text-black/40">No collaborator splits.</td></tr>@endforelse
        </tbody></table></div><div class="mt-4">{{ $releases->links() }}</div></section>
    </div></div>
</x-app-layout>
